import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const { positionsDescription, intendedAction } = body as {
    positionsDescription?: string;
    intendedAction?: string;
  };

  const baseText =
    (positionsDescription || "").slice(0, 200) +
    " | " +
    (intendedAction || "").slice(0, 200);

  // Very simple, deterministic "mock AI" heuristic for demo purposes.
  const lower = baseText.toLowerCase();
  let riskLevel = 1;
  if (lower.includes("leveraged") || lower.includes("leverage")) riskLevel = 3;
  if (lower.includes("max") || lower.includes("all in")) riskLevel = 4;
  if (lower.includes("degen") || lower.includes("ape")) riskLevel = 5;

  const explanation =
    "This is a mocked AI response. Based on your description, the move appears to carry a risk level of " +
    riskLevel +
    " out of 5. In a production system, this explanation would be generated by an LLM that sees your actual Mantle positions and protocol data.";

  const suggestion =
    riskLevel >= 4
      ? "Consider reducing size or leverage, or diversifying across additional protocols to keep risk below your onchain policy limits."
      : "This looks broadly consistent with a moderate risk profile. Still, confirm that your exposure and leverage stay within your onchain policy settings before executing.";

  return NextResponse.json({
    riskLevel,
    explanation,
    suggestion
  });
}

